name: build-and-push
on:
  push:
    branches: [ main, test ]
permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push image
        env:
          IMAGE: ghcr.io/microfix/sqp_generator:${{ github.ref_name }}
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t "$IMAGE" \
            --push \
            .
